export const UPDATE_VARIABLES = 'UPDATE_VARIABLES';
export const DELETE_VARIABLES = 'DELETE_VARIABLES';
export const UPDATE_IMAGENES = 'UPDATE_IMAGENES';
export const DELETE_IMAGENES = 'DELETE_IMAGENES';
